  
 
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Impendulo.Common.Enum
{

        public enum EnumAddressTypes : int
	    {
Postal = 1,Residential = 2        }
        public enum EnumContactTypes : int
	    {
Email_Address = 1,Cell_Number = 2,Home_Number = 3,Office_Number = 4,Fax_Number = 2007        }
        public enum EnumCountries : int
	    {
South_Africa = 1,Lesotho = 2,Mozambique = 3,Zimbabwe = 4,Namibia = 5        }
        public enum EnumDepartments : int
	    {
Learnership = 1004,Lifting_Operator_Training_LOPT = 1005,Surface_Mobile_Equipment = 1006,Apprenticeship = 2004,Short_Courses = 2005,Training_Related_Services = 2009,test = 5014        }
        public enum EnumDisabilities : int
	    {
Mobility_Impairments = 1,Physical_Impairments = 2,Vision = 3,Hearing = 4,Cognitive_or_Learning = 5,Other = 7        }
        public enum EnumEmailMessageRepositoryHistoryTrancationTypes : int
	    {
NewMessage = 1,MessageSent = 2        }
        public enum EnumEnquiryStatuses : int
	    {
New = 1,Enrollment_In_Progress = 2,Awaiting_Scheduling = 3,Schedule_Finalised = 4,Enquiry_Closed = 5        }
        public enum EnumEnrollentDocumentTypes : int
	    {
Enrollment_Documents = 1,ID_Documents = 2,Proof_Of_Payment = 3        }
        public enum EnumEnrollmentProgressStates : int
	    {
In_Progress = 1,Complete = 2        }
        public enum EnumEnrollmentTypes : int
	    {
Novice = 1,ReCertification = 2        }
        public enum EnumEquiryHistoryTypes : int
	    {
Company_Contact_Selection = 1,Curriculum_Selection = 2,Equiry_Responded_And_Accepted = 3,Equiry_Responded_And_Closed = 4,Enquiry_Initial_Consultation_Completed = 1003,Enquiry_Initial_Documentation_Sent = 1004,Enquiry_Custom_Email_Message_Sent = 1005        }
        public enum EnumEthnicities : int
	    {
Black_African = 1,White = 2,Coloured = 3,Indian = 4,Asian = 5,Other_Unspecified = 6        }
        public enum EnumGenders : int
	    {
Male = 1,Female = 2        }
        public enum EnumMartialStatuses : int
	    {
Married = 1,Widowed = 2,Separated = 3,Divorced = 4,Single = 5        }
        public enum EnumProcesses : int
	    {
Enquiry = 1,Enrollment = 2        }
        public enum EnumProcessSteps : int
	    {
An_Enquiry_Capture_Completed = 1,Enquiry__Apprenticeship__Step_1__Documentation_To_Send = 3        }
        public enum EnumProvinces : int
	    {
Gauteng = 1,Free_State = 2,Western_Cape = 3,Northern_Cape = 4,Eastern_Cape = 5,Limpopo = 6,KwaZuluNatal = 7,Mpumalanga = 8,North_West = 9        }
        public enum EnumQualificationLevels : int
	    {
NQF_1_Grade_9_National_Certificate = 1,NQF_2_National_Certificate = 2,NQF_3_National_Certificate = 3,NQF_4_Grade_12_Matric = 4,NQF_5_National_Diplomas = 5,NQF_6_National_Diplomas = 6,NQF_7_Bachelors_Degree,_B_Techs,_Advanced_Diploma = 7,NQF_8_Honours_Degree_Postgraduate_Diploma = 8,NQF_9_Masters_Degree = 9,NQF_10_Doctrate = 10        }
        public enum EnumSectionalEnrollmentTypes : int
	    {
Section_13 = 1,Section_28 = 2        }
        public enum EnumSetas : int
	    {
Construction_Education_and_Training_Authority = 2,Transport_Education_Training_Authority = 3,Mining_Qualifications_Authority = 4        }
        public enum EnumTitles : int
	    {
Mr = 1,Mrs = 2,Miss = 3,Dr = 4,Prof = 5        }
        public enum EnumTypeOfRelations : int
	    {
Father = 1,Mother = 2,Brother = 3,Sister = 4,Uncle = 5,Aunt = 6,Friend = 7,Husband = 8,Wife = 9,Girl_Friend = 10,Boy_Friend = 11        }
}




