//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Impendulo.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CurriculumEnquiry
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CurriculumEnquiry()
        {
            this.CurriculumEquirySelectedCourses = new ObservableListSource<CurriculumEquirySelectedCours>();
            this.Enrollments = new ObservableListSource<Enrollment>();
        }
    
        public int CurriculumEnquiryID { get; set; }
        public int EnquiryID { get; set; }
        public int CurriculumID { get; set; }
        public int EnquiryStatusID { get; set; }
        public System.DateTime LastUpdated { get; set; }
        public int EnrollmentQuanity { get; set; }
        public bool InitialCurriculumEnquiryDocumentationSent { get; set; }
    
        public virtual Curriculum Curriculum { get; set; }
        public virtual Enquiry Enquiry { get; set; }
        public virtual LookupEnquiryStatus LookupEnquiryStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableListSource<CurriculumEquirySelectedCours> CurriculumEquirySelectedCourses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableListSource<Enrollment> Enrollments { get; set; }
    }
}
