//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Impendulo.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class File
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public File()
        {
            this.ApprenticeshipEnrollmentDocuments = new ObservableListSource<ApprenticeshipEnrollmentDocument>();
            this.EmailMessageRepositories = new ObservableListSource<EmailMessageRepository>();
            this.MessageTemplates = new ObservableListSource<MessageTemplate>();
        }
    
        public int ImageID { get; set; }
        public string ContentType { get; set; }
        public byte[] FileImage { get; set; }
        public string FileName { get; set; }
        public string FileExtension { get; set; }
        public System.DateTime DateCreated { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableListSource<ApprenticeshipEnrollmentDocument> ApprenticeshipEnrollmentDocuments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableListSource<EmailMessageRepository> EmailMessageRepositories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableListSource<MessageTemplate> MessageTemplates { get; set; }
    }
}
