//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Impendulo.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        public int ScheduleID { get; set; }
        public System.DateTime ScheduleStartDate { get; set; }
        public System.DateTime ScheduleCompletionDate { get; set; }
        public int EnrollmentID { get; set; }
        public int CurriculumCourseID { get; set; }
    
        public virtual CurriculumCourse CurriculumCours { get; set; }
        public virtual Enrollment Enrollment { get; set; }
    }
}
